version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis
    volumes:
      - myapp-redis:/var/lib/redis/data:rw
  web:
    build: .
    command: bash -c "bundle check || bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./src:/myapp
      - gems:/gems
    ports:
      - "3000:3000"
    env_file:
      - .myapp.env
    tty: true
    stdin_open: true
volumes:
  myapp-redis:
  gems:
